spring:
  application:
    name: feignconsumer
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
service:
   ribbon:
     ConnectTimeOut:25

# feign对请求和响应进行压缩  类型和最小压缩大小
feign:
  compression:
    request:
      mime-types: text/xml, application/xml, application/json
      min-request-size: 2048
    response:
      enabled:true
# 设置日志
logging:
  level:
    feign:DEBUG