spring:
  application:
    name: feignconsumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/



